version: '3'
services:
  api:
    build: .
    environment:

      - USE_DATABASE=false  # Can be set to 'true' to enable database logging
      - POSTGRES_DB=flask_logs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: flask_logs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: