name: Deploy to GCP (Cloud Run)

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: your-gcp-project-id

      - name: Build the Docker image
        run: |
          docker build -t gcr.io/your-gcp-project-id/flask-api:latest .

      - name: Push the Docker image
        run: |
          docker push gcr.io/your-gcp-project-id/flask-api:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flask-api --image gcr.io/your-gcp-project-id/flask-api:latest --region us-central1 --platform managed --allow-unauthenticated